language: node_js
node_js:
  - 16
branches:
  only:
  - master
cache:
  directories:
  - node_modules

jobs:
  install:
    - npm install
    - npm run build
  deploy:
    - provider: s3
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
      bucket: travis-s3-vue
      region: ap-northeast-2
      skip_cleanup: true
      acl: private
      local_dir: dist
      wait-until-deployed: true

  