language: node_js
node_js:
  - 16
branches:
  only:
  - master
cache:
  directories:
  - node_modules

jobs:
  install:
    - npm install
    - npm run build
  deploy:
    - scp -r /dist/* ec2-user@172.31.5.124/home/ec2-user/dist/
  